name: Release

on: 
  pull_request:
    types:
      - closed
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy_prod:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PROD_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROD_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: | 
          supabase link --project-ref $SUPABASE_PROJECT_ID
          supabase db push
          supabase functions deploy personalities
